product-name: p-healthwatch
network-properties:
  singleton_availability_zone:
    name: ((az3))
  other_availability_zones:
  - name: ((az1))
  - name: ((az2))
  - name: ((az3))
  network:
    name: pas
  service_network:
    name: services
product-properties:
  .properties.opsman:
    value: enable
  .properties.opsman.enable.url:
    value: https://opsman.((subdomain-name)).((domain-name))
  .healthwatch-forwarder.health_check_az:
    value: ((region))-a
  .properties.boshtasks:
    value: disable
errand-config:
  smoke-tests:
    post-deploy-state: false
resource-config:
  mysql:
    instances: 1
