---
pivnet-api-token: ((pivnet-api-token-test123))
pivnet-file-glob: p-spring-cloud-services-*.pivotal
pivnet-product-slug: p-spring-cloud-services
product-version-regex: 2\.0\.(.*)
stemcell-iaas: google
