---
pivnet-api-token: dbe9ce017e1145d589034710a42548f1-r
pivnet-file-glob: p_spring-cloud-services-*.pivotal
pivnet-product-slug: p-spring-cloud-services
product-version-regex: 3\.0\.(.*)
stemcell-iaas: google
